// client/src/components/sidemenu.tsx
import { cn } from "@/lib/utils"
import { NavLink } from "react-router"

type Links = {
  label: string;
  path: string
}
const items: Links[] = [
  {
    label: "Home",
    path: "/dashboard"
  },
  {
    label: "New application",
    path: "/job/new"
  },
  {
    label: "Profile",
    path: "/profile"
  }
]

export default function Sidemenu() {
  return (
    <aside className="col-span-2 border rounded-lg p-4 border-gray-200">
      <ul className="flex flex-col gap-2">
        {items.map((item, i) => (
          <li key={i}>
            <NavLink to={item.path} className={({ isActive }) => cn(
              "block px-4 rounded-full py-2 text-sm border border-transparent hover:border-gray-300",
              (isActive && "bg-gray-200")
            )}>
              {item.label}
            </NavLink>
          </li>
        ))}
      </ul>
    </aside>
  )
}

// client-solidjs/src/components/sidemenu.tsx
import { For } from "solid-js"
import { Link, useLocation } from "@tanstack/solid-router"


type Links = {
  label: string;
  path: string;
}
const items: Links[] = [
  {
    label: "Applications",
    path: "/applications",
  },
  {
    label: "New application",
    path: "/applications/new",
  },
  {
    label: "Profile",
    path: "/profile",
  },
  {
    label: "Settings",
    path: "/settings",
  },
  {
    label: "LLM",
    path: "/models",
  }
]

export default function Sidemenu() {
  const location = useLocation()

  return (
    <aside class="m-2 rounded-md bg-zinc-900 ring-1 ring-white/[.07] shadow-[inset_0_1px_0_rgba(255,255,255,.05),0_24px_48px_-24px_rgba(0,0,0,.95)] flex flex-col items-stretch justify-between p-2">
      <ul class="flex flex-col items-stretch gap-2">
        <For each={items}>
          {(item) => (
            <li>
              <Link data-page={location().pathname === item.path} to={item.path} class="block rounded-lg sidenav-btn">
                <span class="text-sm font-semibold">{item.label}</span>
              </Link>
            </li>)}
        </For>
      </ul>
    </aside>
  )
}
