// client/src/routes/application.tsx
import { useParams } from "react-router";
import { Button } from "@/components/ui/button";
import { Link } from "react-router";
import Loading from "@/components/loading";
import type { Application, Skill } from "@/types/api.types";
import InlineEditDropdown from "../components/ui/edit/dropdown-edit";
import Documents from "@/components/documents";
import Actions from "@/components/actions";
import { renderDate } from "@/lib/date";
import Base from "@/components/base";
import Skills from "@/components/skills";
import { GET, POST, PUT } from "@/lib/api";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { toast } from "sonner"
import type { SavedAction } from "@/components/form/action";
import { createPortal } from "react-dom";
import Modal from "@/components/modal";

const statusOptions: string[] = [
  "saved",
  "applied",
  "interviewing",
  "offered",
  "rejected",
  "withdrawn",
];

type ApplicationDetails = {
  application: Application,
  actions: SavedAction[],
  skills: Skill[] | null
}

export default function ApplicationDetail() {
  const [toggleSkillsModal, setToggleSkillsModal] = useState(false)
  const { id } = useParams();
  const { data, isLoading, isSuccess } = useQuery({
    queryKey: ["application", id],
    queryFn: async () => {
      const result = await GET<ApplicationDetails>(`/api/applications/${id}`, null)
      if (result.error) throw result.error
      return result.response!.data
    },
    retry: 0,
  })

  if (isLoading) return <div>Loading ...</div>
  if (!isSuccess || !data) return null

  async function save(obj: { [key: string]: string }) {
    const { error } = await PUT(`/api/applications/${data!.application.id}`, obj)
    if (error) {
      console.error(error)
      toast.error("Something went wrong while trying to save application", { position: "bottom-right" })
      return
    }

    toast.success("Application updated", { position: "bottom-right" })
  }

  const saveSkills = async (skills: Skill[]) => {
    const { error } = await POST<any>(`/api/applications/${data!.application.id}/skills`, { skills })
    if (error) {
      console.error(error)
      toast.error("Something went wrong while trying to update skills", { position: "bottom-right" })
    }
  }

  return (
    <Base className="flex flex-col gap-4">
      <div className="py-4 flex items-center justify-between">
        <Button asChild variant="outline">
          <Link to="/dashboard">Back</Link>
        </Button>
      </div>
      <section className="grid grid-cols-12 gap-4">
        <div className="col-span-9 flex flex-col gap-6">
          <header>
            <InlineEditDropdown name="status" value={data!.application.status}
              onSave={save} options={statusOptions}
            />
            <h1 className="text-3xl mt-4">{data!.application.name}</h1>
            <span className="block text-muted-foreground">{data!.application.position}</span>
          </header>

          <div className="flex flex-col gap-2 border rounded-lg border-gray-200 p-4">
            <div className="flex items-center justify-between">
              <h3 className="text-sm font-semibold mb-3 text-muted-foreground 
              uppercase tracking-wide">
                Skills
              </h3>
              <Button variant="outline" size="sm" onClick={() => setToggleSkillsModal(true)}>
                AI
              </Button>
              {toggleSkillsModal && createPortal(
                <Modal onClose={() => setToggleSkillsModal(false)} title="Generate list of skills">
                  <AISkill applicationID={data.application.id} />
                </Modal>, document.body
              )}

            </div>
            <Skills skills={data!.skills ?? []} update={saveSkills} />
          </div>

          <Documents onUpdate={save} application={data.application} />
          <Actions applicationId={data.application.id} actions={data.actions} />
        </div>

        <div className="flex flex-col col-span-3 gap-2 border rounded-lg border-gray-200 p-4">
          <h2 className="uppercase text-md font-semibold">Details</h2>
          <div>
            <span className="text-md">Created</span>
            <p className="text-sm text-muted-foreground">
              {renderDate(data.application.create_date)}
            </p>
          </div>
          <div>
            <span className="text-md">Company</span>
            <p className="text-sm text-muted-foreground">
              {data.application.company}
            </p>
          </div>
          <div>
            <span className="text-md">Homepage</span>
            <a href={data.application.homepage} target="_blank" className="block text-sm text-muted-foreground hover:underline">
              {data.application.homepage}
            </a>
          </div>
          <div>
            <span className="text-md">Job post</span>
            <a href={data.application.link} target="_blank" className="block text-sm text-muted-foreground hover:underline">
              {data.application.link}
            </a>
          </div>
        </div>
      </section>
    </Base>
  )
}

type AISkillProps = {
  applicationID: string
}

function AISkill(props: AISkillProps) {
  const [isLoading, setIsLoading] = useState(false)
  const [skills, setSkills] = useState<Array<string>>([])

  const generate = async () => {
    setIsLoading(true)
    const result = await GET<{ skills: Array<string> }>(`/api/llm/agent/hardskills?applicationId=${props.applicationID}`, null)
    if (result.error) {
      console.log(result.error)
    }

    setSkills(result.response?.data?.skills ?? [])
    setIsLoading(false)
  }

  return (
    <div className="flex flex-col gap-4">
      <div>
        <Button size="sm" onClick={generate}>
          Generate
        </Button>
      </div>
      <Loading isLoading={isLoading}>
        <div>
          <h3 className="font-bold">Result:</h3>
          <ul className="flex flex-wrap gap-2 mt-1 text-sm">
            {skills.map((skill) => (
              <li key={skill} className="border border-gray-200 px-2 rounded">
                {skill}
              </li>
            ))}
          </ul>
        </div>
      </Loading>
    </div>
  )
}

// client/src/pages/application.tsx
import { createRoute } from "@tanstack/solid-router"
import ApplicationLayout from "./layouts/application"
import { GET, PUT, POST } from "../utils/api"
import { ApplicationStatus, TSavedAction, TSavedApplication, TSkill, TSkillExtended, TSKilLSearch } from "../models/models"
import { renderDate } from "../utils/date"
import Documents from "../components/documents"
import Skills from "../components/skills"
import Actions from "../components/actions"
import SelectField from "../components/input/SelectField"
import { useToast } from "../components/toast"
import { Button, IconButton } from "../components/elements/button"
import { createSignal, For, Show } from "solid-js"
import { Portal } from "solid-js/web"
import { Modal, ModalFooter } from "../components/modal"

type Response = {
  application: TSavedApplication;
  actions: Array<TSavedAction>;
  skills: Array<TSkill>;
}

const applicationRoute = createRoute({
  getParentRoute: () => ApplicationLayout,
  path: '$applicationId',
  component: Application,
  loader: ({ params }) => GET<Response>(`/applications/${params.applicationId}`, null)
})

function Application() {
  const toast = useToast()
  const result = applicationRoute.useLoaderData()

  const updateTags = async (tags: Array<TSkill>) => {
    const { error } = await POST(`/applications/${result().response!.data.application.id}/skills`, { skills: tags })
    if (error) {
      toast.error({ message: "Error occured while trying to save skills" })
      console.error(error)
      return
    }

    toast.success({ message: "Skills updated" })
  }

  const handleUpdate = async (item: { [k: string]: any }) => {
    const { error } = await PUT(`/applications/${result().response!.data.application.id}`, item)
    if (error) {
      toast.error({ message: "Error while trying to update application information" })
      console.error(error)
      return
    }

    toast.success({ message: "Application updated" })
  }

  return (
    <div class="flex flex-col gap-3">

      <header class="py-4 font-semibold flex justify-between items-center">
        <h1 class="font-display uppercase leading-[0.94] text-4xl">{result().response!.data.application.name}</h1>

        <SelectField class="w-max" name="status" value={result().response!.data.application.status} aria-label="Status"
          onInput={(e) => handleUpdate({ status: e.currentTarget.value })}>
          <option value={ApplicationStatus.Saved}>Saved</option>
          <option value={ApplicationStatus.Applied}>Applied</option>
          <option value={ApplicationStatus.Interviewing}>Interviewing</option>
          <option value={ApplicationStatus.Offered}>Offered</option>
          <option value={ApplicationStatus.Rejected}>Rejected</option>
          <option value={ApplicationStatus.Withdrawn}>Withdrawn</option>
        </SelectField>
      </header>
      <section class="flex flex-col gap-2 ring-1 ring-white/20 bg-zinc-800 rounded-lg p-4">
        <header class="flex flex-col gap-4">
          <h3 class="text-sm font-semibold uppercase tracking-wide">Details</h3>

        </header>
        <div class="flex flex-col gap-2">
          <div class="text-sm">
            <h4 class="font-semibold tracking-wide">Created</h4>
            <span class="text-sm font-semibold text-zinc-500">{renderDate(result().response!.data.application.create_date)}</span>
          </div>

          <div class="text-sm">
            <h4 class="font-semibold uppercase tracking-wide">Company</h4>
            <span class="text-sm font-semibold text-zinc-500">{result().response!.data.application.company}</span>
          </div>

          <div class="text-sm">
            <h4 class="font-semibold uppercase tracking-wide">Homepage</h4>
            <a href={result().response!.data.application.homepage} target="_blank" class="text-sm font-semibold text-zinc-500 hover:text-blue-500">
              {result().response!.data.application.homepage}
            </a>
          </div>

          <div class="text-sm">
            <h4 class="font-semibold uppercase tracking-wide">Job post</h4>
            <a href={result().response!.data.application.link} target="_blank" class="text-sm font-semibold text-zinc-500 hover:text-blue-500">
              {result().response!.data.application.link}
            </a>
          </div>
        </div>
      </section>
      <Documents application={result().response!.data.application} onUpdate={handleUpdate} />
      <Skills data={result().response?.data.skills || []} onUpdate={updateTags}>
        <header class="flex items-center justify-between">
          <h3 class="text-sm font-semibold uppercase tracking-wide">Skills</h3>
          <AISkill applicationID={result().response!.data.application.id} />
        </header>
      </Skills>
      <Actions actions={result().response?.data.actions || []} />
    </div>
  )
}

type AISkillProps = {
  applicationID: string;
}

function AISkill(props: AISkillProps) {
  const toast = useToast()
  const [showModal, setshowModal] = createSignal(false)
  const [tags, setTags] = createSignal<Array<TSKilLSearch>>([])
  const [loading, setLoading] = createSignal(false)

  const generate = async () => {
    setLoading(true)
    const result = await GET<Array<TSKilLSearch>>(`/llm/flow/hardskill?applicationId=${props.applicationID}`, null)
    setLoading(false)
    if (result.error) {
      console.error(result.error)
      toast.error({ message: "Something went wrong while trying to generate skills" })
      return
    }

    setTags(() => result.response!.data)
  }


  return (
    <>
      <IconButton icon="ri-ai" label="AI skills popup" size="sm" onClick={() => setshowModal(true)} />
      <Show when={showModal()}>
        <Portal>
          <Modal subTitle="AI" title="Generate skills"
            onClose={() => setshowModal(false)}
            footer={(
              <ModalFooter>
                <Button onClick={generate} variant="outline" label="Generate" loading={loading()} disabled={loading()} />
              </ModalFooter>
            )}>
            <div class="flex flex-wrap gap-2 ring-1 ring-white/20 p-3 rounded-md bg-zinc-950">
              <For each={tags()}>
                {(item) => (
                  <div class="text-xs px-3 py-1 ring-1 flex gap-2 rounded">
                    <span>{item.name}</span>
                  </div>
                )}
              </For>
            </div>
          </Modal>
        </Portal>
      </Show>
    </>
  )
}

export default applicationRoute
