// client/src/routes/llm.tsx
import Base from "@/components/base";
import Loading from "@/components/loading";
import { AvatarBadge } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useNotification } from "@/context/notification";
import { GET, POST } from "@/lib/api";
import { NotificationLLMStatusChange, type LlamaStatusEvent } from "@/types/notification.types";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect } from "react";
import { toast } from "sonner";

type Provider = {
  name: string;
  addr: string;
  available: boolean;
}

export default function Providers() {
  const { data, isLoading } = useQuery({
    queryKey: ["llmProviders"],
    queryFn: async () => {
      const { response, error } = await GET<Provider[]>('/api/llm/providers', null)
      if (error) throw error
      return response!.data || []
    }
  })

  return (
    <Base className="flex flex-col gap-4" showMenu>
      <header className="py-4 font-semibold">
        <h1 className="text-4xl">LLM</h1>
      </header>
      <Loading isLoading={isLoading}>
        <div>
          {data && data.map((provider, i) => (
            <details key={i} className="border rounded">
              <summary className="flex justify-between items-center px-4 py-2">
                <div className="flex flex-col">
                  <span className="block text-lg font-semibold">{provider.name}</span>
                  <span className="block text-sm">{provider.addr}</span>
                </div>
                <div className="flex flex-row gap-2 items-center">
                  {provider.available ? 'Available' : 'Unavailable'}
                  <AvatarBadge className={`${provider.available ? 'bg-green-600' : 'bg-red-600'} relative w-3 h-3`} />
                </div>
              </summary>
              <div className="p-4">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Name</TableHead>
                      <TableHead></TableHead>
                      <TableHead></TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {provider.available && <Models provider={provider.name} />}
                  </TableBody>
                </Table>
              </div>
            </details>
          ))}
        </div>
      </Loading>
    </Base>
  )
}


type Model = {
  id: string;
  status: string
}

type ModelResponse = {
  models: Model[];
  provider: string;
  in_use: string;
}

type ModelsProps = {
  provider: string
}

function Models(props: ModelsProps) {
  const notification = useNotification()
  const queryClient = useQueryClient()
  const { data, isSuccess, refetch } = useQuery({
    queryKey: ["llmModels"],
    queryFn: async () => {
      const result = await GET<ModelResponse>(`/api/llm/providers/${props.provider}/models`, null)
      if (result.error) throw result.error
      return result.response!.data
    },
  })

  useEffect(() => {
    if (notification.type !== NotificationLLMStatusChange || !data) return
    const content = notification.content as LlamaStatusEvent;

    queryClient.setQueryData<ModelResponse>(['llmModels'], (prev) => {
      if (!prev) return prev

      return {
        ...prev,
        models: prev.models.map((model) => (
          (model.id === content.model) ? { ...model, status: content.data.status } : model
        ))
      }
    })

  }, [notification, queryClient])

  if (!isSuccess || !data) return null

  const loadModel = async (model: string) => {
    const { error } = await POST(`/api/llm/providers/${props.provider}/load`, { model })
    if (error) {
      console.error(error)
      toast.error("Something went wrong while trying to load model", { position: "bottom-right" })
      return
    }
    refetch()
  }

  const unloadModel = async (model: string) => {
    const { error } = await POST(`/api/llm/providers/${props.provider}/unload`, { model })
    if (error) {
      console.error(error)
      toast.error("Something went wrong while trying to unload model", { position: "bottom-right" })
      return
    }

    refetch()
  }

  const enableModel = async (model: string) => {
    const { error } = await POST(`/api/llm/providers/${props.provider}/toggle`, { model })

    if (error && error.status !== 500) {
      toast.error(error.message, { position: "bottom-right" })
      return
    } else if (error) {
      console.error(error)
      toast.error("Something went wrong while trying to unload model", { position: "bottom-right" })
      return
    }

    refetch()
  }

  return (
    <>
      {data.models.map((model) => (
        <TableRow key={model.id}>
          <TableCell>{model.id}</TableCell>
          <TableCell className="w-30 text-right">
            <Button
              onClick={() => {
                if (model.status === "unloaded") {
                  loadModel(model.id)
                } else {
                  unloadModel(model.id)
                }
              }}
              size="xs" variant="secondary">
              {model.status === "loading" && "Loading"}
              {model.status === "unloaded" && "Load"}
              {model.status === "loaded" && "Unload"}
            </Button>
          </TableCell>
          <TableCell className="w-25 text-right">
            <Button onClick={() => enableModel(model.id)}
              size="xs" variant="secondary">
              {data.in_use && data.in_use.includes(model.id) ? "Enabled" : "Disabled"}
            </Button>
          </TableCell>
        </TableRow>
      ))}
    </>
  )
}

// client/src/pages/llm.tsx
import { createRoute } from "@tanstack/solid-router"
import Layout from "./layouts/base"
import PageHeading from "../components/page-heading"
import { NotificationLLMModelEnabled, NotificationLLMStatusChange, TLlamaStatusEvent, TModelToggleEvent, TProviderModels } from "../models/models"
import { GET, POST } from "../utils/api"
import { For, Index, createResource, Suspense } from "solid-js"
import { useNotification } from "../utils/notification"
import { Button } from "../components/elements/button"
import Badge from "../components/elements/badge"
import { useToast } from "../components/toast"

type Response = {
  items: Array<TProviderModels>,
  in_use: string
}

const llmRoute = createRoute({
  getParentRoute: () => Layout,
  path: 'models',
  component: LLM
})

const fetchProviders = async () => {
  const { response, error } = await GET<Response>("/llm/providers-models", null)
  if (error) throw error
  return response
}

function LLM() {
  const toast = useToast()
  const [result, { mutate }] = createResource(true, fetchProviders, {
    initialValue: { status: 0, data: { in_use: "", items: [] } }
  })


  useNotification<TLlamaStatusEvent>(NotificationLLMStatusChange, (event) => {
    // TODO: Rewrite ugly solution
    // TODO https://www.solidjs.com/tutorial/stores_mutation
    mutate((prev) => {
      if (!prev) return prev

      return {
        ...prev,
        data: {
          ...prev.data,
          items: prev.data.items.map((provider) => {
            if (provider.provider.name !== event.content.provider) {
              return provider
            }

            return {
              ...provider,
              models: provider.models.map((model) => {
                if (model.id !== event.content.model) {
                  return model
                }

                return {
                  ...model,
                  status: event.content.data.status,
                }
              }),
            }
          }),
        },
      }
    })
  })

  useNotification<TModelToggleEvent>(NotificationLLMModelEnabled, (event) => {
    mutate((prev) => {
      if (!prev) return prev

      return { ...prev, data: { ...prev.data, in_use: event.content.model } }
    })
  })

  const loadModel = async (provider: string, model: string) => {
    const { error } = await POST(`/llm/providers/${provider}/load`, { model })
    if (error) {
      toast.error({ message: "Unabled load selected model" })
      console.error(error)
    }

  }

  const unloadModel = async (provider: string, model: string) => {
    const { error } = await POST(`/llm/providers/${provider}/unload`, { model })
    if (error) {
      toast.error({ message: "Unabled unload selected model" })
      console.error(error)
    }
  }

  const useModel = async (provider: string, model: string) => {
    const { error } = await POST(`/llm/providers/${provider}/toggle`, { model })
    if (error) {
      toast.error({ message: "Unabled toggle selected model" })
      console.error(error)
      return
    }
  }

  return (
    <>
      <PageHeading title="Models" />
      <Suspense fallback={<p>Loading ...</p>}>
        <Index each={result()!.data.items}>
          {(item) => {
            return (
              <details class="ring-1 ring-white/20 rounded-lg overflow-hidden">
                <summary class="flex justify-between items-center px-4 py-4 bg-zinc-800 cursor-pointer">
                  <div class="flex flex-col">
                    <span class="block text-lg font-semibold">{item().provider.name}</span>
                    <span class="block text-sm">{item().provider.addr}</span>
                  </div>
                  <div class="flex flex-row gap-4 items-center">
                    <Badge class="text-sm" variant={item().provider.available ? 'offered' : 'rejected'} label={item().provider.available ? 'Available' : 'Unavailable'} />
                    <span class="block text-xs text-zinc-500">{item().models.length} models</span>
                  </div>
                </summary>
                <div class="p-4">
                  <table class="table">
                    <thead>
                      <tr>
                        <th>Name</th>
                        <th class="text-center">Action</th>
                        <th class="text-center">On</th>
                      </tr>
                    </thead>
                    <tbody>
                      <For each={item().models}>
                        {(model) => {
                          return (
                            <tr>
                              <td>{model.id}</td>
                              <td class="capitalize w-20">
                                <div class="flex justify-center">
                                  <Button class="w-full" onClick={() => {
                                    if (model.status === "loaded") unloadModel(item().provider.name, model.id)
                                    if (model.status === "unloaded") loadModel(item().provider.name, model.id)
                                  }} label={model.status} variant={model.status === "loaded" ? "primary" : "outline"} disabled={model.status === "loading"} />
                                </div>
                              </td>
                              <td class="w-20 text-center">
                                <input onChange={() => useModel(item().provider.name, model.id)} type="checkbox"
                                  checked={result()!.data.in_use.includes(model.id)}
                                  disabled={model.status !== "loaded"}
                                  class="toggle border-0 ring-1 ring-white/20 bg-zinc-500 checked:bg-emerald-400 text-zinc-800 checked:text-zinc-950" />
                              </td>
                            </tr>
                          )
                        }}
                      </For>
                    </tbody>
                  </table>
                </div>
              </details>
            )
          }}
        </Index>
      </Suspense>
    </>
  )
}

export default llmRoute
