// client-solidjs/src/components/work-history.tsx
import type { TSavedWorkHistory, TWorkHistory } from "../models/models"
import { workHistorySchema } from "../models/models"
import { DeleteConfirmationDialog } from "./alert-dialog";
import { Modal, ModalFooter } from "./modal"
import { createSignal, For, Show } from "solid-js"
import { Portal } from "solid-js/web";
import { createForm } from "@tanstack/solid-form"
import { Button, IconButton } from "./elements/button";
import InputField from "./input/InputField";
import TextareaField from "./input/TextareaField";
import DateField from "./input/DateField";
import BooleanField from "./input/BooleanField";
import { DELETE, POST, PUT } from "../utils/api";
import { useToast } from "./toast";

type Props = {
  data: Array<TSavedWorkHistory>
}

export default function WorkHistory(props: Props) {
  const toast = useToast()
  const [workHistory, setWorkHistory] = createSignal(props.data)
  const [showModal, setShowModal] = createSignal<{ [k: string]: boolean }>({})

  const toggleTargetModal = (id: string, value: boolean) => {
    setShowModal({ ...showModal(), [id]: value })
  }

  const handleDelete = async (id: string) => {
    const { error } = await DELETE(`/profile/history/${id}`, null)
    if (error) {
      toast.error({ message: "Error occurred while tyring to delete history entry" })
      console.error(error)
      return
    }

    setWorkHistory(workHistory().filter((item) => item.id !== id))

    toast.success({ message: "Entry deleted" })
  }

  const saveWorkHistoryItem = (item: TSavedWorkHistory) => {
    setWorkHistory([...workHistory(), item])
  }

  const updateWorkHistoryItem = (item: TSavedWorkHistory) => {
    setWorkHistory(workHistory().map((history) => history.id === item.id ? item : history))
  }

  return (
    <div class="flex flex-col gap-2 rounded-lg p-4 ring-1 ring-white/20 bg-zinc-800">
      <header class="flex items-center justify-between">
        <h3 class="text-sm font-semibold uppercase tracking-wide">Work history</h3>
        <IconButton size="sm" icon="ri-add-line" label="New experience entry" onClick={() => toggleTargetModal("new-history", true)} />
        <Show when={showModal()["new-history"]}>
          <Portal>
            <FormWorkExperience onSuccess={saveWorkHistoryItem} title="New entry"
              action="create" toggleVisibility={() => toggleTargetModal("new-history", false)} />
          </Portal>
        </Show>
      </header>
      <ul class="flex flex-col gap-2">
        <For each={workHistory()}>
          {(item) => (
            <li class="flex items-center gap-4 text-sm border-l-2 border-border pl-4">
              <div class="flex-1 flex flex-col">
                <h3 class="font-semibold">{item.title}</h3>
                <span class="block">{item.company}</span>
              </div>
              <div class="flex gap-2">
                <IconButton icon="ri-eye-line" size="sm" label="Edit entry" onClick={() => toggleTargetModal(item.id, true)} />
                <Show when={showModal()[item.id]}>
                  <Portal>
                    <FormWorkExperience title="Edit entry" onSuccess={updateWorkHistoryItem}
                      action="update" toggleVisibility={() => toggleTargetModal(item.id, false)} item={item} />
                  </Portal>
                </Show>
                <DeleteConfirmationDialog id="delete-application"
                  title="Are you sure, you want to delete selected item"
                  description={`You are currently deleting (${item.title}).`}
                  onCancel={() => toggleTargetModal(item.id, false)}
                  onConfirmation={() => handleDelete(item.id)} />
              </div>
            </li>
          )}
        </For>
      </ul>
    </div>
  )
}

type FormWorkExperienceProps = {
  title: string
  action: 'update' | 'create'
  item?: TSavedWorkHistory
  toggleVisibility: () => void
  onSuccess?: (item: TSavedWorkHistory) => void
}

const defaultHistoryValues: TWorkHistory = {
  company: "",
  title: "",
  description: "",
  start_date: 0,
  end_date: 0,
  current: false,
}

function FormWorkExperience(props: FormWorkExperienceProps) {
  const toast = useToast()
  const form = createForm(() => ({
    defaultValues: props.item || defaultHistoryValues,
    validators: {
      onSubmit: workHistorySchema
    },
    onSubmit: async ({ value }) => {
      if (props.action === 'create') {
        const result = await POST<TSavedWorkHistory>(`/profile/history`, value)
        if (result.error) {
          toast.error({ message: "Error occurred while trying to create experience" })
          console.error(result.error)
        }

        if (props.onSuccess) props.onSuccess(result!.response!.data)
        toast.success({ message: "Experience created" })
      } else {
        const { id, ...data } = value as TSavedWorkHistory
        const result = await PUT(`/profile/history/${props.item!.id}`, data)
        if (result.error) {
          toast.error({ message: "Error occurred while trying to update experience" })
          console.error(result.error)
        }

        if (props.onSuccess) props.onSuccess(value as TSavedWorkHistory)
        toast.success({ message: "Experience updated" })
      }
    }
  }))

  const handleSubmit = async () => {
    await form.handleSubmit()
    if (form.state.isValid) {
      props.toggleVisibility()
    }
  }

  return (
    <Modal subTitle="Work history" title={props.title}
      onClose={props.toggleVisibility}
      footer={(
        <ModalFooter>
          <Button onClick={() => props.toggleVisibility()} variant="outline" label="Cancel" />
          <Button onClick={() => handleSubmit()} variant="primary" label="Save entry" />
        </ModalFooter>
      )}>
      <form id="work-history-form" onSubmit={(e) => {
        e.preventDefault()
        e.stopPropagation()
      }}>
        <form.Field name="company"
          children={(field) => (
            <InputField label="Company" name={field().name}
              value={field().state.value}
              onInput={(e) => field().handleChange(e.currentTarget.value)}
              onBlur={field().handleBlur}
              errors={field().state.meta.errors.map((err) => err?.message || "")}
            />
          )} />

        <form.Field name="title"
          children={(field) => (
            <InputField label="Job title" name={field().name}
              value={field().state.value}
              onInput={(e) => field().handleChange(e.currentTarget.value)}
              onBlur={field().handleBlur}
              errors={field().state.meta.errors.map((err) => err?.message || "")}
            />
          )} />

        <form.Field name="description"
          children={(field) => (
            <TextareaField label="Description" name={field().name}
              value={field().state.value}
              onInput={(e) => field().handleChange(e.currentTarget.value)}
              onBlur={field().handleBlur}
              errors={field().state.meta.errors.map((err) => err?.message || "")}
            />
          )} />

      </form>

      <div class="flex gap-4">
        <form.Field name="start_date"
          children={(field) => (
            <DateField label="Start date" name={field().name} value={field().state.value}
              onChange={(e) => field().handleChange(e)}
              onBlur={field().handleBlur}
              errors={field().state.meta.errors.map((err) => err?.message || "")}
            />
          )} />

        <form.Subscribe
          selector={(state) => state.values.current}
          children={(current) => (
            <form.Field name="end_date"
              children={(field) => (
                <DateField disabled={current()} label="End date" name={field().name} value={field().state.value}
                  onChange={(e) => field().handleChange(e)}
                  onBlur={field().handleBlur}
                  errors={field().state.meta.errors.map((err) => err?.message || "")}
                />
              )} />
          )}
        />

        <form.Field name="current"
          children={(field) => (
            <BooleanField label="Current" name={field().name} checked={field().state.value}
              onChange={(e) => field().handleChange(e.target.checked)}
              onBlur={field().handleBlur}
              errors={field().state.meta.errors.map((err) => err?.message || "")}
            />
          )} />

      </div>
    </Modal>
  )
}

// client/src/components/workHistory.tsx
import { Button } from "./ui/button"
import { RiEyeLine } from "@remixicon/react"
import HistoryForm, { UpdateHistoryForm } from "./form/history"
import type { SavedWorkHistory, WorkHistory } from "./form/history"
import { useState } from "react"
import { DeleteConfirmationDialog } from "./dialog/alert-dialog"
import { DELETE } from "@/lib/api"
import { toast } from "sonner"
import { createPortal } from "react-dom"
import Modal from "./modal"

type Props = {
  data: SavedWorkHistory[]
}
export default function WorkHistory(props: Props) {
  const [modalOpenState, setModalOpenState] = useState<{ [k: string]: boolean }>({})
  const [history, setHistory] = useState(props.data)

  const toggleTargetModal = (id: string, value: boolean) => {
    setModalOpenState({ ...modalOpenState, [id]: value })
  }

  const handleSave = (id: string, data: WorkHistory) => {
    setHistory((prev) =>
      prev.map((item) => (item.id === id ? { ...item, ...data } : item))
    )
  }

  const handleDelete = async (id: string) => {
    const { error } = await DELETE(`/api/profile/history/${id}`, null)
    if (error) {
      console.error(error)
      toast.success("Could not delete current work history", { position: "bottom-right" })
      return
    }

    setHistory((prev) => (
      prev.filter((item) => item.id !== id)
    ))
    toast.success("Work history deleted", { position: "bottom-right" })
  }

  return (
    <div className="bg-card border rounded-lg p-6">
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wide">Work history</h3>
        <Button variant="outline" size="sm" onClick={() => toggleTargetModal("new-experience", true)}>
          + Add work history
        </Button>
        {modalOpenState["new-experience"] && createPortal(
          <Modal title="New work experience" onClose={() => toggleTargetModal("new-experience", false)}>
            <HistoryForm
              onCancel={() => toggleTargetModal("new-experience", false)}
              onSubmit={(data: SavedWorkHistory) => {
                setHistory((prev) => [...prev, data])
                toggleTargetModal("new-experience", false)
              }}
            />
          </Modal>, document.body
        )}
      </div>

      {history.length === 0 && (
        <p className="text-sm text-muted-foreground">No work history saved</p>
      )}

      {history.length > 0 && (
        <div className="space-y-3">
          {history.map((history) => (
            <div key={history.id} className="flex gap-4 text-sm border-l-2 border-border pl-4">
              <div className="flex-1">
                <h3 className="font-semibold">{history.company}</h3>
                <span>{history.title}</span>
              </div>

              <div className="space-y-2">
                <Button type="button" variant="ghost"
                  size="icon-sm"
                  aria-label="View history"
                  className="shrink-0 cursor-pointer"
                  onClick={() => toggleTargetModal(history.id, true)}>
                  <RiEyeLine />
                </Button>

                {modalOpenState[history.id] && createPortal(
                  <Modal title="View history" onClose={() => toggleTargetModal(history.id, false)}>
                    <UpdateHistoryForm history={history} onSave={handleSave} />
                  </Modal>, document.body
                )}

                <DeleteConfirmationDialog buttonLabel="Delete work history"
                  title="Are you sure, you want to delete selected item"
                  description={`You are currently deleting (${history.title}) history.`}
                  onConfirmation={() => handleDelete(history.id)}
                />
              </div>
            </div>
          ))}
        </div>
      )}

    </div>
  )
}
